spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  data:
    redis:
      port: ${SPRING_REDIS_PORT:6379}
      host: ${SPRING_REDIS_HOST:redis}